# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import pages.models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('wagtailcore', '0028_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('in_home_stream', models.BooleanField(default=True, verbose_name='Include in Homepage Stream')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', wagtail.wagtailcore.fields.RichTextField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            bases=(models.Model, pages.models.PhotoPresenter),
        ),
        migrations.CreateModel(
            name='PhotoPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.Photo')),
            ],
            options={
                'verbose_name': 'photo placement',
                'verbose_name_plural': 'photo placements',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StreamInclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='wagtailcore.Page')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.Stream')),
            ],
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BasePage')),
                ('previews_per_page', models.IntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.basepage', pages.models.Pagination),
        ),
        migrations.CreateModel(
            name='RichTextPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.BasePage')),
                ('body', wagtail.wagtailcore.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.basepage',),
        ),
        migrations.AddField(
            model_name='basepage',
            name='preview_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('indexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.IndexPage')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.Stream')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('pages.indexpage',),
        ),
        migrations.CreateModel(
            name='PhotoIndexPage',
            fields=[
                ('indexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.IndexPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.indexpage',),
        ),
        migrations.CreateModel(
            name='PhotoPage',
            fields=[
                ('richtextpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.RichTextPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.richtextpage',),
        ),
        migrations.AddField(
            model_name='photoplacement',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_placements', to='pages.PhotoPage'),
        ),
    ]
