# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('pages', '0002_photo_photopage_photoplacement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoplacement',
            options={'ordering': ['sort_order'], 'verbose_name': 'photo placement', 'verbose_name_plural': 'photo placements'},
        ),
        migrations.AddField(
            model_name='photopage',
            name='preview_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
