# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_indexpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexPage',
            new_name='PhotoIndexPage',
        ),
    ]
