# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20160808_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('indexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.IndexPage')),
            ],
            options={
                'verbose_name': 'SB Home Page',
            },
            bases=('pages.indexpage',),
        ),
    ]
