# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='in_home_stream',
            field=models.BooleanField(default=True, verbose_name='Include in Homepage Stream'),
        ),
        migrations.AddField(
            model_name='photoindexpage',
            name='in_home_stream',
            field=models.BooleanField(default=True, verbose_name='Include in Homepage Stream'),
        ),
        migrations.AddField(
            model_name='richtextpage',
            name='in_home_stream',
            field=models.BooleanField(default=True, verbose_name='Include in Homepage Stream'),
        ),
    ]
