# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_footerlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterLink',
        ),
    ]
